"""Generate the BOX UI font subset from Noto Sans CJK SC (SIL OFL 1.1)."""
import argparse
import pathlib
import re
import subprocess
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
BOARD = ROOT / 'main/boards/alientek/atk-dnesp32s3-box'


def ui_codepoints():
    source = (BOARD / 'box_menu_display.cc').read_text()
    return sorted(set(range(32, 127)) | {ord(c) for c in source if ord(c) > 127})


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--font', required=True, help='NotoSansCJK-Regular.ttc')
    parser.add_argument('--converter', default='lv_font_conv', help='lv_font_conv 1.5.3 executable')
    args = parser.parse_args()
    from fontTools.ttLib import TTCollection
    collection = TTCollection(args.font)
    font = next(f for f in collection.fonts if any(
        n.nameID == 1 and n.toUnicode() == 'Noto Sans CJK SC' for n in f['name'].names))
    codepoints = ui_codepoints()
    missing = set(codepoints) - set(font.getBestCmap())
    if missing:
        raise ValueError('Source font lacks: ' + ''.join(map(chr, sorted(missing))))
    with tempfile.TemporaryDirectory() as directory:
        source_font = pathlib.Path(directory) / 'box-ui-source.otf'
        font.save(source_font)
        for size in (14, 20):
            name = f'box_menu_font_{size}'
            output = BOARD / (name + '.c')
            subprocess.run([args.converter, '--font', str(source_font), '--size', str(size),
                            '--bpp', '4', '--format', 'lvgl', '--no-compress', '--no-prefilter',
                            '--range', ','.join(hex(x) for x in codepoints),
                            '--lv-font-name', name, '--lv-include', 'lvgl.h', '-o', str(output)], check=True)
            text = output.read_text()
            text = re.sub(r' \* Opts: .*', ' * Generated by scripts/generate_box_fonts.py; see BOX-FONT-LICENSE.txt.', text)
            output.write_text(text.rstrip() + '\n')
            print(name, 'glyphs:', len(codepoints))


if __name__ == '__main__':
    main()
